import { Header } from "../ui/header";

const dims = [["Publication fit", "Does the angle belong in the selected Indian Express Group publication?"], ["Newsworthiness", "Why does this matter today, and is there a dateable hook?"], ["Impact", "Who is affected, and how broadly?"], ["Originality", "Does the copy go beyond what any outlet could report?"], ["Sourcing", "Are credible human voices represented across contested sides?"], ["Hook potential", "Is the lead clear, immediate and ideally 20–25 words?"], ["Audience engagement", "Are the stakes clear to a reader with no prior context?"]];
const coachingChecks = [["Human element", "Is there a named person through whose experience the story is told?"], ["Lead and front-loading", "Is the most important fact in the first two paragraphs, under 30 words?"], ["Mission and emotion", "Does the story make the reader feel something?"], ["Declutter and clarity", "Does every sentence earn its place?"], ["Jargon and acronyms", "Are all technical terms explained on first use?"], ["Quote quality", "Are quotes specific and attributed to a named human source?"], ["So what?", "Does the story tell the reader why it matters to them?"]];

export default function EditorialFramework() {
  return <><Header active="standards"/><main className="page"><section className="page-head"><p className="eyebrow">DCT AI INDEPENDENT — DIGITAL COACHING TOOL · V2.2_F · READ-ONLY REFERENCE</p><h1>The editorial framework behind every coaching check.</h1><p>DCT coaches the copy, not the person. It identifies one primary challenge, grounds it in a paragraph and asks a question rather than supplying a rewrite.</p></section><FrameworkSection label="EDITORIAL READINESS" heading="Seven dimensions" items={dims}/><FrameworkSection label="COACHING CHECKS" heading="Seven coaching checks" items={coachingChecks}/><section className="standards-grid"><article className="card"><p className="eyebrow">NON-NEGOTIABLE</p><h2>Sourcing primacy</h2><p>When one side of a contested story has a human voice and the other has none, sourcing becomes the primary coaching note. Institutions and documents are not human sources.</p></article><article className="card"><p className="eyebrow">HOUSE RULES</p><h2>Copy and headlines</h2><ul><li>UK English throughout</li><li>73–76 headline characters</li><li>Maximum two permitted acronyms</li><li>All copy acronyms expanded on first use</li><li>Standalone banned-word list takes priority</li></ul></article><article className="card"><p className="eyebrow">OUTPUT DISCIPLINE</p><h2>Never rewrite</h2><p>Every rewriting impulse becomes a paragraph-specific coaching question. DCT shows strong craft alongside weaknesses so repeatable decisions are visible.</p></article><article className="card"><p className="eyebrow">HUMAN CONTROL</p><h2>Editorial judgement remains final</h2><p>DCT may identify a verification need or structural risk. It cannot establish legal accuracy, fabricate missing context or replace a reporter or editor’s verification.</p></article></section></main></>;
}

function FrameworkSection({ label, heading, items }: { label: string; heading: string; items: string[][] }) {
  return <section className="card wide"><p className="eyebrow">{label}</p><h2 className="section-title">{heading}</h2><div className="dimensions">{items.map((item, index) => <div className="dimension" key={item[0]}><b>{index + 1}</b><div><h3>{item[0]}</h3><p>{item[1]}</p></div></div>)}</div></section>;
}
